swift_version: 2.2
author: Romain Menke
author_url: https://github.com/romainmenke
module: Jenerator
github_url: https://github.com/romainmenke/Jenerator
skip_undocumented: true
min_acl: private
clean: true
source_dir: /Users/romainmenke/Swift/src/github.com/romainmenke/Jenerator/Jenerator
