language: objective-c

matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8

script:
- xcodebuild clean build test -project Jenerator.xcodeproj -scheme JeneratorSDK GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
