language: objective-c
xcode_project: Jenerator.xcodeproj
xcode_scheme: JeneratorUnitTests
branches:
  only:
    - master
git:
  submodules: false
before_install: git submodule update --init --recursive
matrix:
  include:
    - osx_image: xcode7.3
      env: TRAVIS_SWIFT_VERSION=2.2
