language: objective-c
osx_image: xcode7.3

script:
- xcodebuild clean build test -project Jenerator.xcodeproj -scheme JeneratorUnitTests GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
